routes/message.py
from flask_mail import Message, Mail
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.simple_model import Messages, User
from routes import current_user, login_required

from secret import admin_mail

mail = Mail()
main = Blueprint('message', __name__)
"""
邮件相关页面
包括
    收发的所有邮件
    编辑发送电子邮件
    邮件详细信息
    发布新话题
"""


@main.route('/')
@login_required
def index():
    # 返回邮件页面
    # 包括站内私信和发送的电子邮件
    u = current_user()

    sent_mail = Messages.all(sender_id=u.id)
    received_mail = Messages.all(receiver_id=u.id)

    t = render_template(
        'mail/index.html',
        send=sent_mail,
        received=received_mail,
    )
    return t


@main.route("/add", methods=["POST"])
@login_required
def add():
    # 发电子邮件
    form = request.form.to_dict()
    form['receiver_id'] = int(form['receiver_id'])
    u = current_user()
    form['sender_id'] = u.id

    r = User.one(id=form['receiver_id'])
    m = Message(
        subject=form['title'],
        body=form['content'],
        sender=admin_mail,
        recipients=[r.email]
    )
    mail.send(m)

    m = Messages.new(form)
    return redirect(url_for('.index'))





@main.route('/view/<int:id>')
@login_required
def view(id):
    # 返回邮件详细信息
    mail = Messages.one(id=id)
    u = current_user()
    # if u.id == mail.receiver_id or u.id == mail.sender_id:
    if u.id in [mail.receiver_id, mail.sender_id]:
        return render_template('mail/detail.html', mail=mail)
    else:
        return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.simple_model import Topic
from routes import current_user, login_required

main = Blueprint('topic', __name__)
"""
话题相关页面
包括
    topic 详细页面
    编辑新话题页面
    发布新话题
"""


@main.route('/<int:id>')
def detail(id):
    # 返回 topic 详细页面
    t = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=t)


@main.route("/add", methods=["POST"])
@login_required
def add():
    # 发布新话题， 成功后跳转到新话题详细页面
    form = request.form.to_dict()
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
@login_required
def new():
    # 返回编辑新话题的页面
    return render_template("topic/new.html")

routes/user.py
import uuid
import os

from werkzeug.utils import redirect
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    session,
)

from models.simple_model import User
from routes import current_user, login_required

main = Blueprint('user', __name__)
"""
用户相关页面
包括
    注册
    登录
    个人主页
    个人设置

用户登录后, 会写入 session, 并且定向到 首页
"""


@main.route("/login/view", methods=['GET'])
def login_view():
    # 返回用户登录界面
    return render_template("user/login_view.html")


@main.route("/register/view", methods=['GET'])
def register_view():
    # 返回用户注册界面
    return render_template("user/register_view.html")


@main.route("/register", methods=['POST'])
def register():
    # 用户注册处理函数
    # 注册成功， 定向的登录界面
    # 失败， 返回注册页面
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    if u is not None:
        return redirect(url_for('.login_view'))
    else:
        return redirect(url_for('.register_view'))


@main.route("/login", methods=['POST'])
def login():
    # 用户登录处理函数
    # 成功， 定向到首页, 设置 session
    # 失败， 返回登录页面
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.login_view'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('index.index'))


@main.route("/<int:id>")
@login_required
def detail(id):
    # 返回到用户主页， 主页包含用户发表话题，回复等
    user = User.one(id=id)
    topics = user.topics()
    replies = user.replies()

    return render_template("user/detail.html", user=user, topics=topics, replies=replies)


@main.route('/setting')
@login_required
def setting():
    # 返回到用户设置页面，可在该页面对用户资料进行更改
    u = current_user()
    return render_template('user/setting.html', user=u)


@main.route('/setting/save', methods=['POST'])
@login_required
def save_setting():
    # 保存设置
    u = current_user()
    form = request.form.to_dict()
    User.update(u.id, **form)

    return redirect(url_for('.setting'))


@main.route('/setting/changepass', methods=['POST'])
@login_required
def change_pass():
    # 更改密码， 然后跳转到登录页面
    u = current_user()
    form = request.form.to_dict()
    if u.password == User.salted_password(form['old_pass']):
        User.update(u.id, password=User.salted_password(form['new_pass']))
    return redirect(url_for('.login'))


@main.route('/image/add', methods=['POST'])
@login_required
def avatar_add():
    # 上传用户图片
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/index.min.css">
    <link rel="stylesheet" href="/static/css/pure-min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <head>
<body>

<!-- navbar -->
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class="brand" href="{{ url_for('index.index') }}">SEIZER</a>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('index.index') }}">首页</a></li>
                <li><a href="{{ url_for('message.index') }}">邮件</a></li>
                <li><a href="{{ url_for('user.setting') }}">设置</a></li>
                <li><a href="{{ url_for('user.register_view') }}">注册</a></li>
                <li><a href="{{ url_for('user.login_view') }}">登录</a></li>

            </ul>
            <a class="btn btn-navbar" id="responsive-sidebar-trigger">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
        </div>
    </div>
</div>

{% block main %}
{% endblock %}

</body>

templates/index.html
{% extends "base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar"  href="{{ url_for('user.detail', id=user.id) }}" >
                            <img src="{{ user.image }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('user.detail', id=user.id) }}">{{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                            {{ user.signature }}
                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            {# count(t.replies()) #}
                            {# <span>{{ t.reply_count() }} / {{ t.views }}</span> #}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}