models/topic.py
# from sqlalchemy import Integer, Column, Unicode, UnicodeText
#
# from models.base_model import SQLMixin, db
# from models.user import User
# from models.reply import Reply
#
#
# class Topic(SQLMixin, db.Model):
#     views = Column(Integer, nullable=False, default=0)
#     title = Column(Unicode(50), nullable=False)
#     content = Column(UnicodeText, nullable=False)
#     user_id = Column(Integer, nullable=False)
#
#     @classmethod
#     def new(cls, form, user_id):
#         form['user_id'] = user_id
#         m = super().new(form)
#         return m
#
#     @classmethod
#     def get(cls, id):
#         m = cls.one(id=id)
#         m.views += 1
#         m.save()
#         return m
#
#     def user(self):
#         u = User.one(id=self.user_id)
#         return u
#
#     def replies(self):
#         rs = Reply.all(topic_id=self.id)
#         return rs
#
#     def reply_count(self):
#         count = len(self.replies())
#         return count

routes/reply.py
from flask import (
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.simple_model import Reply, User, Messages
from routes import current_user, login_required

main = Blueprint('reply', __name__)
"""
回复相关页面
包括
    添加回复
    @ 站内私信
"""


@main.route("/add", methods=["POST"])
@login_required
def add():
    # 添加回复
    # 确认回复中是否有 @ 其他用户，有则发私信
    # 完成后返回到对应话题详细页面
    form = request.form.to_dict()
    u = current_user()
    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, content)
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, content):
    # 发站内私信
    print('send_mail', sender, receivers, content)
    for r in receivers:
        form = dict(
            title='AT  【{}】'.format(r.username),
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )
        Messages.new(form)

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.simple_model import Topic
from routes import current_user, login_required

main = Blueprint('topic', __name__)
"""
话题相关页面
包括
    topic 详细页面
    编辑新话题页面
    发布新话题
"""


@main.route('/<int:id>')
def detail(id):
    # 返回 topic 详细页面
    t = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=t)


@main.route("/add", methods=["POST"])
@login_required
def add():
    # 发布新话题， 成功后跳转到新话题详细页面
    form = request.form.to_dict()
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
@login_required
def new():
    # 返回编辑新话题的页面
    return render_template("topic/new.html")

routes/user.py
import uuid
import os

from werkzeug.utils import redirect
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    session,
)

from models.simple_model import User
from routes import current_user, login_required

main = Blueprint('user', __name__)
"""
用户相关页面
包括
    注册
    登录
    个人主页
    个人设置

用户登录后, 会写入 session, 并且定向到 首页
"""


@main.route("/login/view", methods=['GET'])
def login_view():
    # 返回用户登录界面
    return render_template("user/login_view.html")


@main.route("/register/view", methods=['GET'])
def register_view():
    # 返回用户注册界面
    return render_template("user/register_view.html")


@main.route("/register", methods=['POST'])
def register():
    # 用户注册处理函数
    # 注册成功， 定向的登录界面
    # 失败， 返回注册页面
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    if u is not None:
        return redirect(url_for('.login_view'))
    else:
        return redirect(url_for('.register_view'))


@main.route("/login", methods=['POST'])
def login():
    # 用户登录处理函数
    # 成功， 定向到首页, 设置 session
    # 失败， 返回登录页面
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.login_view'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('index.index'))


@main.route("/<int:id>")
@login_required
def detail(id):
    # 返回到用户主页， 主页包含用户发表话题，回复等
    user = User.one(id=id)
    topics = user.topics()
    replies = user.replies()

    return render_template("user/detail.html", user=user, topics=topics, replies=replies)


@main.route('/setting')
@login_required
def setting():
    # 返回到用户设置页面，可在该页面对用户资料进行更改
    u = current_user()
    return render_template('user/setting.html', user=u)


@main.route('/setting/save', methods=['POST'])
@login_required
def save_setting():
    # 保存设置
    u = current_user()
    form = request.form.to_dict()
    User.update(u.id, **form)

    return redirect(url_for('.setting'))


@main.route('/setting/changepass', methods=['POST'])
@login_required
def change_pass():
    # 更改密码， 然后跳转到登录页面
    u = current_user()
    form = request.form.to_dict()
    if u.password == User.salted_password(form['old_pass']):
        User.update(u.id, password=User.salted_password(form['new_pass']))
    return redirect(url_for('.login'))


@main.route('/image/add', methods=['POST'])
@login_required
def avatar_add():
    # 上传用户图片
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))

templates/topic/detail.html
{% extends "base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
                <span class="topic_full_title">
                    {{ topic.title }}
                </span>
                <div class="changes">
                    <span>
                        发布于 2 天前
                    </span>
                    <span>
                        作者
                        <a href="{{ url_for('user.detail', id=topic.user().id) }}">
                            {{ topic.user().username }}
                        </a>
                    </span>
                    <span>
                        {{ topic.views }} 次浏览
                    </span>
                    <span>
                        来自 问答
                    </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
        {% set u = r.user() %}
        <div class='cell reply_area reply_item'>
            <div class='user_info'>
                <a class='dark reply_author'>
                    {{ u.username }}
                </a>
                <a class="reply_time">
                    {{ loop.index }}楼 / {{ loop.length }}楼 •
                    <span class="time" data-created_time="{{ r.created_time }}"></span>
                </a>
            </div>
            <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
            </div>
            <div class='reply_content from-leiwei1991'>
                <div class="markdown-text">{{ r.content }}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div>
        <form action="{{ url_for('reply.add') }}" method="post">
            <input type="hidden" name="topic_id" value="{{ topic.id }}">
            <textarea name="content"></textarea>
            <button>添加回复</button>
        </form>
    </div>
</div>
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent, contentDiv.innerHTML)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var registerTimer = function () {
        setInterval(function () {
            var times = es('.time')
            for (var i = 0; i < times.length; i++) {
                var t = times[i]
                var time = Number(t.dataset.created_time)
                var now = Math.floor(new Date() / 1000)
                var delta = now - time
                var s = `${delta} 秒前`
                t.innerText = s
            }
        }, 1000)
    }

    var __main = function () {
        markContents()
        highlight()
        registerTimer()
    }

    __main()

</script>
{% endblock %}

templates/topic/new.html
{% extends "base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class="panel">
            <div class="inner post">
                <form id="create_topic_form" method="post" action="{{ url_for('topic.add') }}">
                    <fieldset>
                        <textarea class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                        <div class='markdown_editor in_editor'>
                            <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                    <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
  (sfunction () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
{% endblock %}