models/user.py
#
# from sqlalchemy import Column, String
#
# from models.base_model import SQLMixin, db
#
#
#
# class User(SQLMixin, db.Model):
#     """
#     User 是一个保存用户数据的 model
#     现在只有两个属性 username 和 password
#     """
#
#     username = Column(String(50), nullable=False)
#     password = Column(String(256), nullable=False)
#
#     @classmethod
#     def salted_password(cls, password, salt='$!@><?>HUI&DWQa`'):
#         import hashlib
#         def sha256(ascii_str):
#             return hashlib.sha256(ascii_str.encode('ascii')).hexdigest()
#
#         hash1 = sha256(password)
#         hash2 = sha256(hash1 + salt)
#         print('sha256', len(hash2))
#         return hash2
#
#     def hashed_password(self, pwd):
#         import hashlib
#         # 用 ascii 编码转换成 bytes 对象
#         p = pwd.encode('ascii')
#         s = hashlib.sha256(p)
#         # 返回摘要字符串
#         return s.hexdigest()
#
#     @classmethod
#     def register(cls, form):
#         name = form.get('username', '')
#         pwd = form.get('password', '')
#         if len(name) > 2 and User.one(username=name) is None:
#             u = User.new(form)
#             u.password = u.salted_password(pwd)
#             u.save()
#             return u
#         else:
#             return None
#
#     @classmethod
#     def validate_login(cls, form):
#         user = User.one(username=form['username'])
#         if user is not None and user.password == User.salted_password(form['password']):
#             return user
#         else:
#             return None
#
#     # def ctopics(self):
#     #     ms = Topic.all(user_id=self.id)
#     #     return ms
#     #
#     # def rtopics(self):
#     #     rs = Reply.all(user_id=self.id)
#     #     ms = []
#     #     for r in rs:
#     #         m = User.one(id=r.user_id)
#     #         ms.append(m)
#     #     return ms

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.simple_model import Topic
from routes import current_user, login_required

main = Blueprint('topic', __name__)
"""
话题相关页面
包括
    topic 详细页面
    编辑新话题页面
    发布新话题
"""


@main.route('/<int:id>')
def detail(id):
    # 返回 topic 详细页面
    t = Topic.get(id)

    # 不应该放在路由里面
    # m.views += 1
    # m.save()

    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=t)


@main.route("/add", methods=["POST"])
@login_required
def add():
    # 发布新话题， 成功后跳转到新话题详细页面
    form = request.form.to_dict()
    u = current_user()
    m = Topic.new(form, user_id=u.id)
    return redirect(url_for('.detail', id=m.id))


@main.route("/new")
@login_required
def new():
    # 返回编辑新话题的页面
    return render_template("topic/new.html")

routes/user.py
import uuid
import os

from werkzeug.utils import redirect
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    session,
)

from models.simple_model import User
from routes import current_user, login_required

main = Blueprint('user', __name__)
"""
用户相关页面
包括
    注册
    登录
    个人主页
    个人设置

用户登录后, 会写入 session, 并且定向到 首页
"""


@main.route("/login/view", methods=['GET'])
def login_view():
    # 返回用户登录界面
    return render_template("user/login_view.html")


@main.route("/register/view", methods=['GET'])
def register_view():
    # 返回用户注册界面
    return render_template("user/register_view.html")


@main.route("/register", methods=['POST'])
def register():
    # 用户注册处理函数
    # 注册成功， 定向的登录界面
    # 失败， 返回注册页面
    form = request.form
    # 用类函数来判断
    u = User.register(form)
    if u is not None:
        return redirect(url_for('.login_view'))
    else:
        return redirect(url_for('.register_view'))


@main.route("/login", methods=['POST'])
def login():
    # 用户登录处理函数
    # 成功， 定向到首页, 设置 session
    # 失败， 返回登录页面
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.login_view'))
    else:
        # session 中写入 user_id
        session['user_id'] = u.id
        # 设置 cookie 有效期为 永久
        session.permanent = True
        return redirect(url_for('index.index'))


@main.route("/<int:id>")
@login_required
def detail(id):
    # 返回到用户主页， 主页包含用户发表话题，回复等
    user = User.one(id=id)
    topics = user.topics()
    replies = user.replies()

    return render_template("user/detail.html", user=user, topics=topics, replies=replies)


@main.route('/setting')
@login_required
def setting():
    # 返回到用户设置页面，可在该页面对用户资料进行更改
    u = current_user()
    return render_template('user/setting.html', user=u)


@main.route('/setting/save', methods=['POST'])
@login_required
def save_setting():
    # 保存设置
    u = current_user()
    form = request.form.to_dict()
    User.update(u.id, **form)

    return redirect(url_for('.setting'))


@main.route('/setting/changepass', methods=['POST'])
@login_required
def change_pass():
    # 更改密码， 然后跳转到登录页面
    u = current_user()
    form = request.form.to_dict()
    if u.password == User.salted_password(form['old_pass']):
        User.update(u.id, password=User.salted_password(form['new_pass']))
    return redirect(url_for('.login'))


@main.route('/image/add', methods=['POST'])
@login_required
def avatar_add():
    # 上传用户图片
    file = request.files['avatar']

    # ../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
    path = os.path.join('images', filename)
    file.save(path)

    u = current_user()
    User.update(u.id, image='/images/{}'.format(filename))

    return redirect(url_for('.setting'))

templates/user/detail.html
{% extends "base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><span class="divider"></span></li>
                </ul>
            </div>
            <div class="inner userinfo">
                <div class="user_big_avatar">
                    <img src="{{ user.image }}" class="user_avatar">
                </div>
                <a class="dark">{{ user.username }}</a>
                <div class="user_profile">
                </div>
                <p class="col_fade">注册时间
                    <a class="dark">{{ user.created_time | formatted_time }}</a>
                </p>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">最近创建的话题</span>
            </div>
            {% for t in topics %}
            <div class="cell">
                <a class="user_avatar pull-left">
                    <img src="{{ user.image }}">
                </a>
                <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                    </span>
                <span class="last_time pull-right">
                        <span class="time" data-time="{{ t.created_time }}"></span>
                </span>
                <div class="topic_title_wrapper">
                    <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                        {{ t.title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">最近参与的话题</span>
            </div>
            {% for r in replies %}
            <div class="cell">
                <a class="user_avatar pull-left">
                    <img src="{{ user.image }}">
                </a>
                <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ r.topic().replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ r.topic().views }}
                        </span>
                    </span>
                <span class="last_time pull-right">
                        <span class="time" data-time="{{ r.created_time }}"></span>
                </span>
                <div class="topic_title_wrapper">
                    <a class="topic_title" href="{{ url_for('topic.detail', id=r.topic().id) }}">
                        {{ r.topic().title }}
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/user/login_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>login</title>
    <link href="/static/css/main.css" rel="stylesheet">
</head>
<body class="EntrySign-body">
<div id="root">
    <div data-zop-usertoken="{}" data-reactroot="">
        <div class="LoadingBar"></div>
        <main role="main" class="App-main">
            <div class="SignFlowHomepage">
                <div class="SignFlowHomepage-content">
                    <div class="Card SignContainer-content">
                        <div class="SignFlowHeader" style="padding-bottom:5px">
                            <div class="SignFlowHeader-slogen">SEIZE THE DAY, NOW</div>
                        </div>
                        <div class="SignContainer-inner">
                            <div class="Login-content">
                                <form novalidate="" class="SignFlow" method="post" action="{{ url_for('user.login') }}">
                                    <div class="SignFlow-account">
                                        <div class="SignFlow-supportedCountriesSelectContainer"></div>
                                        <div class="SignFlowInput SignFlow-accountInputContainer">
                                            <div class="SignFlow-accountInput Input-wrapper"><input type="text" value=""
                                                                                                    name="username"
                                                                                                    class="Input"
                                                                                                    placeholder="用户名">
                                            </div>
                                            <div class="SignFlowInput-errorMask SignFlowInput-requiredErrorMask SignFlowInput-errorMask--hidden"></div>
                                        </div>
                                    </div>
                                    <div class="SignFlow-password">
                                        <div class="SignFlowInput">
                                            <div class="Input-wrapper"><input type="password" value="" name="password"
                                                                              class="Input" placeholder="密码"></div>
                                            <div class="SignFlowInput-errorMask SignFlowInput-requiredErrorMask SignFlowInput-errorMask--hidden"></div>
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="Button SignFlow-submitButton Button--primary Button--blue">登录
                                    </button>
                                </form>
                            </div>
                            <div class="SignContainer-switch">没有帐号？<a href="{{ url_for('user.register_view') }}">注册</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

templates/user/register_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>register</title>
    <link href="/static/css/main.css" rel="stylesheet">
</head>
<body class="EntrySign-body">
<div id="root">
    <div data-zop-usertoken="{}" data-reactroot="">
        <div class="LoadingBar"></div>
        <main role="main" class="App-main">
            <div class="SignFlowHomepage">
                <div class="SignFlowHomepage-content">
                    <div class="Card SignContainer-content">
                        <div class="SignFlowHeader" style="padding-bottom:5px">
                            <div class="SignFlowHeader-slogen">SEIZE THE DAY, NOW</div>
                        </div>
                        <div class="SignContainer-inner">
                            <div class="Login-content">
                                <form novalidate="" class="SignFlow" method="post" action="{{ url_for('user.register') }}">
                                    <div class="SignFlow-account">
                                        <div class="SignFlow-supportedCountriesSelectContainer"></div>
                                        <div class="SignFlowInput SignFlow-accountInputContainer">
                                            <div class="SignFlow-accountInput Input-wrapper"><input type="text" value=""
                                                                                                    name="username"
                                                                                                    class="Input"
                                                                                                    placeholder="用户名">
                                            </div>
                                            <div class="SignFlowInput-errorMask SignFlowInput-requiredErrorMask SignFlowInput-errorMask--hidden"></div>
                                        </div>
                                    </div>
                                    <div class="SignFlow-password">
                                        <div class="SignFlowInput">
                                            <div class="Input-wrapper"><input type="password" value="" name="password"
                                                                              class="Input" placeholder="密码"></div>
                                            <div class="SignFlowInput-errorMask SignFlowInput-requiredErrorMask SignFlowInput-errorMask--hidden"></div>
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="Button SignFlow-submitButton Button--primary Button--blue">注册
                                    </button>
                                </form>
                            </div>
                            <div class="SignContainer-switch">已有帐号？<a href="{{ url_for('user.login_view') }}">登录</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
</body>
</html>

templates/user/setting.html
{% extends "base.html" %}
{% block title %}bbs club{% endblock%}
{% block main %}
<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar"  href="{{ url_for('user.detail', id=user.id) }}" >
                            <img src="{{ user.image }}">
                        </a>
                        <span class="user_name">
                            <a class="dark" href="{{ url_for('user.detail', id=user.id) }}">{{ user.username }}
                            </a>
                        </span>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            “
                            {{ user.signature }}
                            ”
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="inner">
                <a href="{{ url_for('topic.new') }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="{{ url_for('user.detail', id=user.id) }}">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">
                <form id="setting_form" class="form-horizontal" action="{{ url_for('.save_setting') }}" method="post">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>
                        <div class="controls">
                            <input class="input-xlarge readonly" id="name" name="name" size="30" type="text"
                                   readonly="true"
                                   value="{{user.username}}">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>

                        <div class="controls">
                            <textarea class="input-xlarge" id="signature" name="signature"
                                      size="30">{{user.signature}}</textarea>
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="保存中.." value="保存设置">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.change_pass') }}"
                      method="post">
                    <div class="control-group">
                        <label class="control-label" for="old_pass">当前密码</label>
                        <div class="controls">
                            <input class="input-xlarge" type="password" id="old_pass" name="old_pass" size="30">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="new_pass">新密码</label>
                        <div class="controls">
                            <input class="input-xlarge" type="password" id="new_pass" name="new_pass" size="30">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="更改密码">
                    </div>
                </form>
            </div>
        </div>
        <div class="panel">
            <div class="header">
                <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
                <img src="{{ user.image }} ">
                <form id="avatar_add" class="form-horizontal" action="{{ url_for('.avatar_add') }}" method="post"
                      enctype="multipart/form-data">
                    <div class="control-group">
                        <div class="controls">
                            <input type="file" name="avatar">
                        </div>
                    </div>
                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" data-loading-text="更改中.." value="上传头像">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}